[package]
name = "user-profile-server"
version = "0.1.0"
authors = ["D1plo1d <thatotherdude@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
# juniper = "0.14.2"
# juniper_hyper = "0.5.2"
# hyper  = "0.13.1"

tokio = { version = "0.2", features = ["full"] }
warp = "0.2.2"
futures = { version = "0.3.4", features = ["compat"] }
futures-util = "0.3.4"
# reqwest = { version = "0.9.19" }

juniper = { git = "https://github.com/graphql-rust/juniper" }

log = "0.4"
pretty_env_logger = "0.3"
reqwest = { version = "0.10", features = ["json"] }
# tokio = { version = "0.2", features = ["full"] }
# futures03 = { package = "futures", version = "0.3.1", features = ["compat"] }
# futures = { package = "futures", version = "0.1.29" }
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.44"
url = "2.1.1"
sqlx = { version = "0.3.0-alpha.2", features = ["postgres", "chrono"] }
sqlx-core = { version = "0.3.0-alpha.2" }
rand = "0.7.3"
error-chain = "0.12.2"
bcrypt = "0.6"
cookie = "0.13.3"
consistenttime = "0.2.0"
base64 ="0.11.0"
async-trait = "0.1.24"
ring = "0.16.11"
chrono = { version = "0.4.10", features = ["serde"] }
frank_jwt = "3.1.2"
surf = "2.0.0-alpha.0"
http-client = { version = "1.1.1", features = ["native_client"] }
openssl = "0.10.28"

gravatar = "0.2.0"
